# Generated by Django 2.2 on 2022-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customersupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupport',
            options={'ordering': ('title',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
