# Generated by Django 3.0.14 on 2022-11-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221129_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSupport',
        ),
    ]
