# Generated by Django 3.0.14 on 2022-11-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customersupport_customersupportcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSupportCategory',
        ),
    ]
