# Generated by Django 3.0.14 on 2022-12-06 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_customersupportcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
