# Generated by Django 3.0.14 on 2022-12-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bookdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bookDate',
            new_name='book_date',
        ),
    ]
