# Generated by Django 2.2 on 2022-12-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braintree_id',
        ),
    ]
